Singin layout and SingInFragment.kt
akai-org/movies-mobile pull request #29
Opened 2019-11-11 21:07 UTC by V-Ader

idk if it works

2019-11-12 20:01 UTC, Kossa123 requested changes

2019-11-12 20:01 UTC, Kossa123 commented on app/src/main/java/pl/org/akai/movies/fragments/SignInFragment.kt
> +
dodaj on success listener i żeby otwierał się kolejny fragment,
warto także dodać obsługę błędów np złe hasło, brak internetu, nie istniejący user to wszystko jest rzucane w onF ailureListenerze

2019-11-12 20:01 UTC, Kossa123 commented on app/src/main/res/layout/fragment_singin.xml
> +
Poczytaj o TextInputLayout i TextInputEditText zamiast editText'ów

2019-11-25 19:58 UTC, V-Ader reviewed
it should be ok

2019-11-26 18:00 UTC, merged